name: Docker Web Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t mi-web .

      - name: Run container
        run: docker run mi-web
